import './drift_database.dart';

final modelMap = {
  'app_settings': database.appSetting,
  'sync_queue': database.syncQueue,
  'athlete_guardian': database.athleteGuardian,
  'athlete_meet_event': database.athleteMeetEvent,
  'athlete_sign_up_form': database.athleteSignUpForm,
  'athlete_status': database.athleteStatus,
  'athlete': database.athlete,
  'category': database.category,
  'club': database.club,
  'discipline_type': database.disciplineType,
  'discipline': database.discipline,
  'group_athlete': database.groupAthlete,
  'group_trainer': database.groupTrainer,
  'group': database.group,
  'guardian': database.guardian,
  'item_type': database.itemType,
  'item': database.item,
  'meet_event': database.meetEvent,
  'meet': database.meet,
  'remote_config': database.remoteConfig,
  'school_year': database.schoolYear,
  'sign_up_form_status': database.signUpFormStatus,
  'sign_up_form': database.signUpForm,
  'trainer_status': database.trainerStatus,
  'trainer': database.trainer,
  'training_athlete': database.trainingAthlete,
  'training_time': database.trainingTime,
  'training_trainer': database.trainingTrainer,
  'training': database.training,
  'web_post': database.webPost,
}